# [DB]方式设置
# [DB JPA]设置
spring:
  jpa:
    show-sql: true
    properties:
      ddl-auto: create
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
# [DB Mybatis]
# [DB Connector]
spring.datasource:
    name: QGZWXX
    username: QGZWXX_user
    password: gx@123321
# [oracle]
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.200.195:1433;DatabaseName=QGZWXX
    # 下面为连接池的补充设置，应用到上面所有数据源中# 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    max-active: 50
    # 配置获取连接等待超时的时间
    maxWait: 90000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 30000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 180000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true

server: 
     port: 8888
  
# [log4j]设置
logging:
    config: classpath:log4j.properties
